#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_SETTINGSDLG                 101
#define IDD_ABOUTDLG                    103
#define IDD_NEWLANG                     105
#define IDC_SETTINGS_HELP               1000
#define IDC_EDIT_PREFIX                 1001
#define IDC_GITHUB                      1001
#define IDC_EDIT_FORMAT                 1002
#define IDC_EDIT_LANG                   1002
#define IDC_VERSION                     1002
#define IDC_README                      1003
#define IDC_RAD_FUNCTION                1004
#define IDC_BTN_REMOVE                  1006
#define IDC_CMB_LANG                    1007
#define IDC_EDIT_START                  1008
#define IDC_EDIT_LINE                   1009
#define IDC_EDIT_END                    1010
#define IDC_EDIT_PREVIEW                1011
#define IDC_BTN_ADD                     1012
#define IDC_CHB_ALIGN                   1013
#define IDC_RAD_FILE                    1014

// From PythonScript for the Console
#define IDD_DIALOG1                     201
#define IDB_PNG1                        202
#define IDD_CONSOLE                     204
#define IDD_SCRIPTCONFIG                205
#define IDI_FOLDERCLOSED                207
#define IDI_FOLDEROPEN                  208
#define IDI_ICON3                       209
#define IDI_PYTHON                      209
#define IDB_PYTHON                      210
#define IDI_PYTHON8                     213
#define IDI_ICON1                       214
#define IDD_PROMPTDIALOG                216
#define IDB_PYTHONPOWERED               218
#define IDC_RUN                         2002
#define IDC_PROMPT                      2003
#define IDC_FILETREE                    2004
#define IDC_RADMACHINE                  2005
#define IDC_RADUSER                     2006
#define IDC_LIST1                       2007
#define IDC_MENUITEMLIST                2007
#define IDC_MENUADD                     2008
#define IDC_MENUREMOVE                  2009
#define IDC_LIST2                       2010
#define IDC_TOOLBARITEMLIST             2010
#define IDC_TOOLBARADD                  2011
#define IDC_TOOLBARREMOVE               2012
#define IDC_TOOLBARITEMLIST2            2013
#define IDC_TOOLBARSETICON              2014
#define IDC_LISTMENUITEM                2015
#define IDC_COMBOINITIALISATION         2016
#define IDC_USERTEXT                    2017
#define IDC_COPYRIGHT                   2018
#define IDC_CHECKPREFERINSTALLEDPYTHON  2020
